import {useEffect,useMemo,useState} from 'react';
import {dateInDays,durationDays} from '../domain.js';

type Row={id:string;number:number;no:string;date:string;unit:string;useLocation:string;item:string;amount:number;form2:string;inventoryNo:string;note:string;sourceEvidence:string;cancelled:boolean;cancelReason:string;form1Path?:string;form2Path?:string;version:number};
type Form={date:string;unit:string;useLocation:string;item:string;amount:string;form2:string;inventoryNo:string;note:string;sourceEvidence:string};
type Register={rows:Row[];next:string;masterImported:number;masterExpected:number};
type Preview={records:Row[];alreadyImported:string[];errors:Array<{row?:number;no?:string;error:string}>;canImport:boolean;sourceName:string};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const emptyForm=():Form=>({date:today(),unit:'',useLocation:'',item:'',amount:'',form2:'',inventoryNo:'',note:'',sourceEvidence:''});
const money=(v:number)=>v.toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
function toForm(r:Row):Form{return {date:r.date,unit:r.unit,useLocation:r.useLocation,item:r.item,amount:String(r.amount),form2:r.form2,inventoryNo:r.inventoryNo,note:r.note,sourceEvidence:r.sourceEvidence};}
function recordBody(form:Form){return {...form,amount:Number(form.amount)};}
async function api<T>(path:string,method='GET',body?:unknown):Promise<T>{
  const response=await fetch(path,{method,credentials:'same-origin',cache:'no-store',...(body===undefined?{}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});
  const value=await response.json();if(!response.ok)throw Error(value.error||'เชื่อมต่อระบบไม่สำเร็จ');return value as T;
}
async function fileBase64(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=()=>reject(Error('อ่านไฟล์ไม่สำเร็จ'));reader.readAsDataURL(file);});}
const messageOf=(e:unknown)=>e instanceof Error?e.message:'ทำรายการไม่สำเร็จ';

export default function App(){
  const [register,setRegister]=useState<Register>({rows:[],next:'037',masterImported:0,masterExpected:36});
  const [loaded,setLoaded]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [quickOpen,setQuickOpen]=useState(false),[editRow,setEditRow]=useState<Row|null>(null),[form,setForm]=useState<Form>(emptyForm),[requestKey,setRequestKey]=useState('');
  const [uploadOpen,setUploadOpen]=useState(false),[pendingPdf,setPendingPdf]=useState<File|null>(null);
  const [cancelRow,setCancelRow]=useState<Row|null>(null),[cancelReason,setCancelReason]=useState('');
  const [dateRow,setDateRow]=useState<Row|null>(null),[receiptDate,setReceiptDate]=useState('');
  const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[unitFilter,setUnitFilter]=useState(''),[sort,setSort]=useState('desc');
  const [lookupBusy,setLookupBusy]=useState(false),[lookupMessage,setLookupMessage]=useState('');
  const [importOpen,setImportOpen]=useState(false),[importFile,setImportFile]=useState<File|null>(null),[preview,setPreview]=useState<Preview|null>(null),[importPayload,setImportPayload]=useState<{filename:string;original:string}|null>(null);
  const currentYear=Number(new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Bangkok',year:'numeric'}).format(new Date()));
  const currentMonth=Number(new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Bangkok',month:'numeric'}).format(new Date()));
  const [statsYear,setStatsYear]=useState(currentYear);

  const load=async()=>{try{const data=await api<Register>('/api/w804');setRegister(data);setLoaded(true);setError('');}catch(e){setError(messageOf(e));}};
  useEffect(()=>{void load();const refresh=()=>{if(document.visibilityState==='visible')void load();};const timer=window.setInterval(refresh,30000);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);};},[]);
  const rows=register.rows;
  const active=rows.filter(r=>!r.cancelled),received=active.filter(r=>dateInDays(r.form2)!==null),pending=active.filter(r=>dateInDays(r.form2)===null);
  const finished=received.map(r=>durationDays(r.date,r.form2)).filter((n):n is number=>n!==null);
  const average=finished.length?Math.round(finished.reduce((a,b)=>a+b,0)/finished.length*10)/10:null;
  const longest=finished.length?Math.max(...finished):null;
  const months=['ม.ค.','ก.พ.','มี.ค.','เม.ย.','พ.ค.','มิ.ย.','ก.ค.','ส.ค.','ก.ย.','ต.ค.','พ.ย.','ธ.ค.'].slice(0,statsYear===currentYear?currentMonth:12);
  const monthStats=months.map((label,index)=>({label,form1:active.filter(r=>{const d=dateInDays(r.date);if(d===null)return false;const t=new Date(d*86400000);return t.getUTCFullYear()===statsYear&&t.getUTCMonth()===index;}).length,form2:received.filter(r=>{const d=dateInDays(r.form2);if(d===null)return false;const t=new Date(d*86400000);return t.getUTCFullYear()===statsYear&&t.getUTCMonth()===index;}).length}));
  const monthlyMax=Math.max(1,...monthStats.flatMap(m=>[m.form1,m.form2]));
  const years=[...new Set([currentYear,...rows.flatMap(r=>{const d=dateInDays(r.date);return d===null?[]:[new Date(d*86400000).getUTCFullYear()];})])].sort((a,b)=>b-a);
  const units=useMemo(()=>[...new Set(rows.map(r=>r.unit))].sort((a,b)=>a.localeCompare(b,'th')),[rows]);
  const visible=rows.filter(r=>{
    const q=query.trim().toLocaleLowerCase('th');
    return (!q||['ว804/'+r.no,r.date,r.unit,r.useLocation,r.item,r.inventoryNo,r.note,r.cancelReason].join(' ').toLocaleLowerCase('th').includes(q))&&(!unitFilter||r.unit===unitFilter)&&(status==='all'||status==='cancelled'&&r.cancelled||status==='active'&&!r.cancelled||status==='pending'&&!r.cancelled&&dateInDays(r.form2)===null||status==='received'&&!r.cancelled&&dateInDays(r.form2)!==null);
  }).sort((a,b)=>sort==='asc'?a.number-b.number:b.number-a.number);
  const beginIssue=()=>{setForm(emptyForm());setEditRow(null);setPendingPdf(null);setRequestKey(crypto.randomUUID());setLookupMessage('');setQuickOpen(true);};
  const beginEdit=(r:Row)=>{setEditRow(r);setForm(toForm(r));setLookupMessage('');};
  const closeForm=()=>{setQuickOpen(false);setEditRow(null);setPendingPdf(null);setLookupMessage('');};
  const saveForm=async()=>{
    if(busy)return;setBusy(true);setError('');
    try{
      if(editRow){await api('/api/w804/'+editRow.id,'PUT',{...recordBody(form),version:editRow.version});setMessage('แก้ไข ว804/'+editRow.no+' โดยคงเลขเดิมแล้ว');}
      else{const form1=pendingPdf?{filename:pendingPdf.name,original:await fileBase64(pendingPdf)}:undefined;const result=await api<{row:Row}>('/api/w804','POST',{record:recordBody(form),requestKey,form1});setMessage('ออกเลข ว804/'+result.row.no+' และบันทึกแล้ว');}
      closeForm();await load();
    }catch(e){setError(messageOf(e));}finally{setBusy(false);}
  };
  const lookup=async()=>{
    const number=form.inventoryNo.trim();const snapshot={...form};setLookupBusy(true);setLookupMessage('');
    try{
      const result=await api<{found:boolean;message?:string;fields?:{inventoryNo:string;unit:string;item:string;amount:number|null;note:string}}>('/api/inventory-lookup?number='+encodeURIComponent(number));
      if(!result.found||!result.fields){setLookupMessage(result.message||'ไม่พบเลข Inventory');return;}
      const fields=result.fields;
      setForm(current=>{
        if(current.inventoryNo.trim()!==number)return current;
        const next={...current};for(const key of ['unit','item','note'] as const)if(!current[key]&&current[key]===snapshot[key])next[key]=fields[key]||'';
        if(!current.amount&&current.amount===snapshot.amount&&fields.amount!==null)next.amount=String(fields.amount);
        return next;
      });
      setLookupMessage((fields.amount??0)>50000?'พบ Inventory แต่วงเงินเกิน 50,000 บาท ไม่สามารถออกเลข ว804 สำหรับวงเงินนี้':'พบข้อมูล Inventory แล้ว เติมเฉพาะช่องที่ยังว่าง กรุณาตรวจข้อมูล');
    }catch(e){setLookupMessage(messageOf(e));}finally{setLookupBusy(false);}
  };
  const cancel=async()=>{if(!cancelRow)return;setBusy(true);setError('');try{await api('/api/w804/'+cancelRow.id+'/cancel','POST',{reason:cancelReason,version:cancelRow.version});setMessage('ยกเลิก ว804/'+cancelRow.no+' แล้ว คงเลขและรายการไว้');setCancelRow(null);await load();}catch(e){setError(messageOf(e));}finally{setBusy(false);}};
  const saveReceipt=async()=>{if(!dateRow)return;setBusy(true);setError('');try{await api('/api/w804/'+dateRow.id,'PUT',{...recordBody(toForm(dateRow)),form2:receiptDate,version:dateRow.version});setMessage('บันทึกวันที่รับ Form 2 ของ ว804/'+dateRow.no+' แล้ว');setDateRow(null);await load();}catch(e){setError(messageOf(e));}finally{setBusy(false);}};
  const attach=async(r:Row,kind:'form1'|'form2',file?:File)=>{if(!file)return;if(!file.name.toLowerCase().endsWith('.pdf')||file.size>12*1024*1024){setError('เลือก PDF ขนาดไม่เกิน 12 MB');return;}setBusy(true);setError('');try{await api('/api/w804/'+r.id+'/documents/'+kind,'POST',{filename:file.name,original:await fileBase64(file)});setMessage('แนบ PDF '+kind+' ของ ว804/'+r.no+' แล้ว');await load();}catch(e){setError(messageOf(e));}finally{setBusy(false);}};
  const inspectImport=async()=>{if(!importFile)return;setBusy(true);setPreview(null);setError('');try{if(importFile.size>5*1024*1024)throw Error('ไฟล์ Import ต้องไม่เกิน 5 MB');const payload={filename:importFile.name,original:await fileBase64(importFile)};setImportPayload(payload);setPreview(await api<Preview>('/api/import/preview','POST',payload));}catch(e){setError(messageOf(e));}finally{setBusy(false);}};
  const commitImport=async()=>{if(!preview?.canImport||!importPayload)return;setBusy(true);setError('');try{const result=await api<{imported:string[]}>('/api/import/commit','POST',{...importPayload,confirmed:true});setMessage('Import Master จริง '+result.imported.length+' รายการแล้ว');setImportOpen(false);setPreview(null);await load();}catch(e){setError(messageOf(e));}finally{setBusy(false);}};

  return <div className="page"><main>
    <div className="page-heading"><div><h1>ทะเบียนและติดตาม ว804</h1><p>จัดซื้อวงเงินไม่เกิน 50,000 บาท</p></div><div className="heading-actions"><a className="download" href="/api/export">ดาวน์โหลดทะเบียน</a></div></div>
    {loaded&&register.masterImported<36&&<div className="warning">ยังไม่ได้ Import Master ครบ: {register.masterImported}/36 รายการ · กันเลข 001–036 ไว้แล้ว เลขใหม่เริ่ม 037 · เลข 035 และ 036 จะคงสถานะ “ยกเลิก” · ตารางแสดงเฉพาะข้อมูลที่บันทึกจริง</div>}
    {error&&<div className="error-message" role="alert">{error}</div>}{message&&<div className="message" role="status">{message}</div>}
    <section className="cards"><div className="card"><label>เลขล่าสุดที่บันทึก</label><strong>{loaded?(rows.length?'ว804/'+Math.max(...rows.map(r=>r.number)).toString().padStart(3,'0'):'—'):'กำลังโหลด'}</strong></div><div className="card next"><label>เลขใหม่ถัดไป</label><strong>{loaded?'ว804/'+register.next:'กำลังโหลด'}</strong></div><div className="card actions"><button disabled={!loaded||busy} onClick={beginIssue}>+ เพิ่มรายการ</button><button disabled={!loaded||busy} onClick={beginIssue}>+ ออกเลขด่วน</button><button className="green" disabled={!loaded||busy} onClick={()=>{setUploadOpen(true);setPendingPdf(null);}}>📄 อัปโหลด Form 1</button><button className="muted" disabled={!loaded||busy} onClick={()=>{setImportOpen(true);setPreview(null);setImportFile(null);setImportPayload(null);}}>Import Master</button></div></section>
    <section className="summary-panel"><h2>สถิติการรับฟอร์ม 2</h2><div className="summary-grid"><div className="summary-tile"><span>ระยะเวลาเฉลี่ย</span><strong>{average===null?'—':average+' วัน'}</strong><small>จาก {finished.length} รายการที่มีวันที่ครบ</small></div><div className="summary-tile received"><span>รับฟอร์ม 2 แล้ว</span><strong>{received.length} รายการ</strong><small>นับเฉพาะรายการที่มีวันที่รับ</small></div><div className="summary-tile pending"><span>รอติดตาม</span><strong>{pending.length} รายการ</strong><small>ยังไม่มีวันที่รับฟอร์ม 2</small></div><div className="summary-tile"><span>ใช้เวลานานที่สุด</span><strong>{longest===null?'—':longest+' วัน'}</strong><small>เฉพาะรายการที่วันที่ครบ</small></div></div><p className="summary-note">คำนวณจากรายการที่บันทึกจริง ไม่รวมรายการยกเลิก และไม่นับวันแรก</p></section>
    <section className="monthly-panel"><div className="monthly-heading"><h2>สถิติรับฟอร์มรายเดือน</h2><label>ปีสถิติ <select value={statsYear} onChange={e=>setStatsYear(Number(e.target.value))}>{years.map(y=><option key={y} value={y}>{y+543}</option>)}</select></label></div><p className="monthly-total">ฟอร์ม 1 รวม <b>{monthStats.reduce((a,m)=>a+m.form1,0)} งาน</b> · ฟอร์ม 2 รวม <b>{monthStats.reduce((a,m)=>a+m.form2,0)} งาน</b> · ในทะเบียน <b>{rows.length} รายการ</b></p><div className="monthly-legend"><span><i className="legend-form1"/>รับฟอร์ม 1</span><span><i className="legend-form2"/>รับฟอร์ม 2</span></div><div className="monthly-bars" role="img" style={{gridTemplateColumns:`repeat(${months.length},minmax(0,1fr))`}} aria-label={monthStats.map(m=>`${m.label} ฟอร์ม 1 ${m.form1} ฟอร์ม 2 ${m.form2}`).join(', ')}>{monthStats.map(m=><div className="monthly-group" key={m.label}><div className="monthly-pair"><div className="monthly-bar-column"><strong>{m.form1}</strong><div className="monthly-bar form1" style={{height:(m.form1/monthlyMax*100)+'%'}}/></div><div className="monthly-bar-column"><strong>{m.form2}</strong><div className="monthly-bar form2" style={{height:(m.form2/monthlyMax*100)+'%'}}/></div></div><b>{m.label}</b></div>)}</div><p className="summary-note">นับวันที่แต่ละฟอร์มแยกกัน · ไม่รวมรายการยกเลิก · ไม่รวม Master ที่ยังไม่ Import</p></section>
    <h3>ทะเบียน ว804 — รายการใหม่อยู่บนสุด</h3><div className="filters"><input aria-label="ค้นหาทะเบียน" placeholder="ค้นหาเลข ว804 / Inventory / หน่วยงาน / รายการ" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="กรองสถานะ" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">ทุกสถานะ</option><option value="active">รายการที่ใช้งาน</option><option value="pending">รอติดตามฟอร์ม 2</option><option value="received">รับฟอร์ม 2 แล้ว</option><option value="cancelled">ยกเลิก</option></select><select aria-label="กรองหน่วยงาน" value={unitFilter} onChange={e=>setUnitFilter(e.target.value)}><option value="">ทุกหน่วยงาน</option>{units.map(unit=><option key={unit}>{unit}</option>)}</select><select aria-label="เรียงเลข" value={sort} onChange={e=>setSort(e.target.value)}><option value="desc">เลขล่าสุดก่อน</option><option value="asc">เลขน้อยก่อน</option></select></div>
    <p className="table-help">พบ {visible.length} จาก {rows.length} รายการ · ลงวันที่รับ Form 2 ได้ก่อนแนบ PDF · ยกเลิกแล้วคงเลขเดิม ไม่ใช้ซ้ำ</p>
    <div className="table"><table><thead><tr><th>เลข ว804</th><th>รับฟอร์ม 1</th><th>หน่วยงาน / สถานที่ใช้</th><th>รายการ / วงเงิน</th><th>รับฟอร์ม 2 / ระยะเวลา</th><th>เอกสาร PDF</th><th>จัดการ</th></tr></thead><tbody>{visible.map(r=><tr className={r.cancelled?'cancelled-row':''} key={r.id}>
      <td data-label="เลขทะเบียน" className="reg-no"><b>ว804/{r.no}</b>{r.cancelled&&<small className="cancelled-label">ยกเลิก</small>}</td><td data-label="รับฟอร์ม 1">{r.date||'—'}</td><td data-label="หน่วยงานและสถานที่"><div className="request-unit">{r.unit}</div><div className="use-location">{r.useLocation||'ไม่ระบุสถานที่'}</div>{r.inventoryNo&&<small>Inventory: {r.inventoryNo}</small>}</td><td data-label="รายการ / วงเงิน"><div className="item-name">{r.item}</div><div className="amount-line">{money(r.amount)} บาท</div>{r.note&&<small>{r.note}</small>}{r.cancelled&&r.cancelReason&&<small className="cancel-reason">{r.cancelReason}</small>}</td><td data-label="รับฟอร์ม 2"><div className="date-status"><strong>{r.cancelled?'ยกเลิก':r.form2||'รอติดตาม'}</strong>{!r.cancelled&&<button className="small-action" disabled={busy} onClick={()=>{setDateRow(r);setReceiptDate('');}}>ลงวันที่</button>}</div><small className="duration-line">{r.cancelled||durationDays(r.date,r.form2)===null?'—':durationDays(r.date,r.form2)+' วัน'}</small></td>
      <td data-label="เอกสาร PDF"><div className="pdf-pair">{(['form1','form2'] as const).map(kind=>{const linked=kind==='form1'?r.form1Path:r.form2Path;return <div className="pdf-part" key={kind}><b>{kind==='form1'?'Form 1':'Form 2'}</b><span className={linked?'attached-badge':'missing-badge'}>{linked?'แนบแล้ว':'ยังไม่มีไฟล์ผูก'}</span><div className="pdf-actions">{linked&&<a className="view-action" href={linked} target="_blank" rel="noopener noreferrer">เปิดดู</a>}<label className="file-action">{linked?'เปลี่ยนไฟล์':'แนบ PDF'}<input type="file" accept=".pdf,application/pdf" disabled={busy} onChange={e=>{void attach(r,kind,e.target.files?.[0]);e.target.value='';}}/></label></div></div>;})}</div></td><td data-label="จัดการ"><div className="row-actions"><button disabled={busy} onClick={()=>beginEdit(r)}>Edit</button>{!r.cancelled&&<button className="cancel-btn" disabled={busy} onClick={()=>{setCancelRow(r);setCancelReason('');}}>ยกเลิก</button>}</div></td>
    </tr>)}{!visible.length&&<tr><td colSpan={7} className="empty-register">{!loaded?'กำลังโหลดทะเบียน...':rows.length?'ไม่พบรายการที่ตรงกับการค้นหา':'ยังไม่มีข้อมูลทะเบียนที่บันทึก — พร้อม Import Master 001–036'}</td></tr>}</tbody></table></div>

    {(quickOpen||editRow)&&<div className="overlay"><form className="modal" role="dialog" aria-modal="true" aria-label={editRow?'แก้ไขรายการ':'ออกเลขด่วน'} onSubmit={e=>{e.preventDefault();void saveForm();}}><h2>{editRow?'แก้ไข ว804/'+editRow.no:'ออกเลขด่วน'}</h2><div className="warning">{editRow?'แก้รายการเดิม คงเลขและสถานะยกเลิกเดิมไว้':'เลขถัดไป ว804/'+register.next+' · ระบบยืนยันเลขเมื่อบันทึกสำเร็จ'}</div><div className="inventory-form"><label htmlFor="inventory-number">เลข Inventory (ถ้ามี)</label><div className="lookup-line"><input id="inventory-number" value={form.inventoryNo} onChange={e=>setForm({...form,inventoryNo:e.target.value})} placeholder="เช่น 69-05508"/><button type="button" disabled={lookupBusy||!form.inventoryNo} onClick={()=>void lookup()}>{lookupBusy?'กำลังค้นหา':'ค้น Inventory'}</button></div>{lookupMessage&&<small role="status">{lookupMessage}</small>}</div>{([['date','วันที่รับ Form 1'],['unit','หน่วยงานผู้ขอ *'],['useLocation','สถานที่/หน่วยงานที่จะนำไปใช้'],['item','รายการ *'],['amount','วงเงินรวม (บาท) *'],['form2','วันที่รับ Form 2 (ถ้ามี)'],['note','หมายเหตุ'],['sourceEvidence','ไฟล์ต้นทาง / เอกสารอ้างอิง']] as Array<[keyof Form,string]>).map(([key,label])=><label key={key}>{label}<input required={['unit','item','amount'].includes(key)} type={key==='amount'?'number':'text'} min={key==='amount'?'0.01':undefined} max={key==='amount'?'50000':undefined} step={key==='amount'?'0.01':undefined} value={form[key]} placeholder={key==='date'||key==='form2'?'YYYY-MM-DD หรือ 19 ก.พ. 69':undefined} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}{pendingPdf&&<p>Form 1 ที่จะแนบ: <b>{pendingPdf.name}</b></p>}{editRow?.cancelled&&<p className="cancelled-label">รายการนี้ยกเลิกแล้ว จะไม่เปิดเลขกลับมาใช้ซ้ำ</p>}{error&&<p className="error" role="alert">{error}</p>}<div className="buttons"><button type="button" className="muted" disabled={busy} onClick={closeForm}>ปิด</button><button disabled={busy||lookupBusy||!form.unit.trim()||!form.item.trim()||Number(form.amount)<=0||Number(form.amount)>50000}>{busy?'กำลังบันทึก...':editRow?'บันทึกแก้ไข':'ยืนยันออกเลข'}</button></div></form></div>}
    {uploadOpen&&<div className="overlay"><div className="modal" role="dialog" aria-modal="true" aria-label="อัปโหลด Form 1"><h2>อัปโหลด Form 1 + เอกสารแนบ</h2><div className="warning">รับ PDF ไม่เกิน 12 MB · ตรวจข้อมูลจากเอกสารและกรอกก่อนยืนยันออกเลข · การอ่านด้วย AI ยังไม่ได้เชื่อมในระบบนี้</div><label>เลือก PDF Form 1 / Spec / ใบเสนอราคา<input type="file" accept=".pdf,application/pdf" onChange={e=>{const f=e.target.files?.[0];if(f&&f.size<=12*1024*1024&&f.name.toLowerCase().endsWith('.pdf')){setPendingPdf(f);setError('');}else{setPendingPdf(null);setError('เลือก PDF ขนาดไม่เกิน 12 MB');}}}/></label>{pendingPdf&&<p>ไฟล์: {pendingPdf.name}</p>}{error&&<p className="error">{error}</p>}<div className="buttons"><button className="muted" onClick={()=>setUploadOpen(false)}>ปิด</button><button disabled={!pendingPdf} onClick={()=>{setForm(emptyForm());setEditRow(null);setRequestKey(crypto.randomUUID());setUploadOpen(false);setQuickOpen(true);}}>กรอกข้อมูลและตรวจเลขก่อนบันทึก</button></div></div></div>}
    {dateRow&&<div className="overlay"><form className="modal" role="dialog" aria-modal="true" aria-label="ลงวันที่รับฟอร์ม 2" onSubmit={e=>{e.preventDefault();void saveReceipt();}}><h2>ลงวันที่รับฟอร์ม 2 — ว804/{dateRow.no}</h2><p>บันทึกวันที่ได้โดยไม่ต้องรอแนบ PDF</p><label htmlFor="receipt-date">วันที่รับฟอร์ม 2</label><input id="receipt-date" type="date" required value={receiptDate} onChange={e=>setReceiptDate(e.target.value)}/>{error&&<p className="error">{error}</p>}<div className="buttons"><button type="button" className="muted" onClick={()=>setDateRow(null)}>ปิด</button><button disabled={busy||!receiptDate}>บันทึกวันที่</button></div></form></div>}
    {cancelRow&&<div className="overlay"><form className="modal" role="dialog" aria-modal="true" aria-label="ยืนยันยกเลิกเลข" onSubmit={e=>{e.preventDefault();void cancel();}}><h2>ยืนยันยกเลิก ว804/{cancelRow.no}</h2><p>{cancelRow.item}</p><div className="warning">เก็บรายการและเลขเดิมไว้ในทะเบียน · ไม่คืนเลขไปใช้ซ้ำ</div><label htmlFor="cancel-reason">เหตุผลการยกเลิก *</label><textarea id="cancel-reason" required className="reason-input" value={cancelReason} onChange={e=>setCancelReason(e.target.value)} rows={3}/>{error&&<p className="error">{error}</p>}<div className="buttons"><button type="button" className="muted" onClick={()=>setCancelRow(null)}>กลับ</button><button className="cancel-confirm" disabled={busy||!cancelReason.trim()}>ยืนยันยกเลิกเลข</button></div></form></div>}
    {importOpen&&<div className="overlay"><div className="modal wide" role="dialog" aria-modal="true" aria-label="Import Master"><h2>Import Master ว804 001–036</h2><p>ใช้ข้อมูลจริงที่ตรวจแล้วจาก Excel 001–031 และ PDF B1-032 ถึง B1-036 · ระบบไม่เดาหรือสร้างข้อมูลแทน</p><p><a href="/api/import/template" className="download">ดาวน์โหลดหัวตาราง CSV แม่แบบ</a></p><div className="warning">เลข 035 และ 036 จะถูกบันทึกเป็น “ยกเลิก” เสมอ · ไม่เขียนทับเลขที่มีข้อมูลแล้ว · Import ไม่เปลี่ยนเลขใหม่ถัดไป</div><label>เลือกไฟล์ JSON / CSV / XLSX<input type="file" accept=".json,.csv,.xlsx" onChange={e=>{setImportFile(e.target.files?.[0]||null);setPreview(null);setImportPayload(null);}}/></label><p className="table-help">คอลัมน์: no, date, unit, useLocation, item, amount, form2, inventoryNo, status, cancelReason, note, sourceEvidence · เลข 032–036 ต้องอ้างชื่อ B1-032 ถึง B1-036 ใน sourceEvidence</p><button disabled={!importFile||busy} onClick={()=>void inspectImport()}>ตรวจ Preview ก่อน Import</button>{preview&&<div className="result"><h3>ผลตรวจ {preview.sourceName}</h3><p>รายการใหม่ {preview.records.length} · ข้อมูลตรงกับที่ Import แล้ว {preview.alreadyImported.length} · ข้อผิดพลาด {preview.errors.length}</p>{preview.errors.map((e,i)=><p className="error" key={i}>แถว {e.row||'—'} เลข {e.no||'—'}: {e.error}</p>)}<div className="import-preview"><table><thead><tr><th>เลข</th><th>หน่วยงาน / รายการ</th><th>วงเงิน</th><th>สถานะ / หลักฐาน</th></tr></thead><tbody>{preview.records.map(r=><tr key={r.no}><td>{r.no}</td><td>{r.unit}<br/>{r.item}</td><td>{money(r.amount)}</td><td>{r.cancelled?'ยกเลิก':'ใช้งาน'}<br/>{r.sourceEvidence}</td></tr>)}</tbody></table></div></div>}{error&&<p className="error" role="alert">{error}</p>}<div className="buttons"><button className="muted" disabled={busy} onClick={()=>setImportOpen(false)}>ปิด</button><button disabled={busy||!preview?.canImport} onClick={()=>void commitImport()}>ยืนยัน Import ข้อมูลจริงที่ตรวจแล้ว</button></div></div></div>}
  </main></div>;
}


